### ISSUE TITLE
GNOME 45 support 

### ISSUE THREAD

**Issue by mikethebos** [sneetsher/keyboard_modifiers_status#10]
GNOME 45 made breaking changes to extensions. This extension needs to be updated.

**Comment by 0xR** [comment]
Same issue.

Any1 aware of an alternative?

**Comment by jezek** [comment]
See #11 
I'm using it, it's working on Manjaro GNOME.

**Comment by mikethebos** [comment]
PR #11 works for me. Thanks, @jezek, for your fork.

It was an easy drop-in replacement of the extension source from gnome.org.

**Comment by sneetsher** [comment]
Thank you @jezek. fix pushed to gnome extension portal.
