### ISSUE TITLE
I can confirm that it works on Ubuntu 20.04

### ISSUE THREAD

**Issue by overthetop** [sneetsher/keyboard_modifiers_status#4]
that's GNOME 3.36.2
thx :)

**Comment by sneetsher** [comment]
Thank you very much @overthetop for testing. I will update the config cover up to that version and may be add few future versions, so users don't have to install it manually and wait till it does break.

Related to #3

**Comment by sneetsher** [comment]
- version support updated in metadata of the extension, 3.32 to 3.40
- new package uploaded to extensions.gnome.org to be visible to users
- list of tested Gnome releases updated in #3
