### ISSUE TITLE
Not working in Fedora 33

### ISSUE THREAD

**Issue by IvanDeFelice76** [sneetsher/keyboard_modifiers_status#6]
It doesn't seem to work on Wayland or Xorg in Fedora 33 Beta.
![Schermata da 2020-10-01 23-51-06](https://user-images.githubusercontent.com/26720956/94867610-d651c300-0441-11eb-86eb-58c2dc586194.png)

**Comment by sneetsher** [comment]
Thank you for reporting it @xzj8b3 

I'm aware of Wayland, We have a report in #5 . Couldn't figure out yet.  Xorg on other hand could work for you now, see #7 . If you wouldn't mind testing it, gnome.org update still in review queue usually (1-2 days ).

**Comment by sneetsher** [comment]
Closing a duplicate of #5, feel free to reopen it. GTK changed much from 3 going to 4. Still couldn't find where modifiers event class were moved in Wayland.
