### ISSUE TITLE
Error on upgrade to gnome-shell 3.38.1

### ISSUE THREAD

**Issue by Isopolito** [sneetsher/keyboard_modifiers_status#7]
Changing line 26 and 27 from:
```
x_fill: true,
y_fill: false,
```
to

```
x_expand: true,
y_expand: false,
```

fixes the issue for me. I don't have time for a PR now but will make one if you want.

Thanks!

**Comment by sneetsher** [comment]
@Isopolito no need. Thank you.

**Comment by thien-do** [comment]
Hi @sneetsher thank you for this. Is it released on https://extensions.gnome.org/extension/975/keyboard-modifiers-status/ ?

**Comment by sneetsher** [comment]
@dvkndn You welcome, not yet I just uploaded it. Still in review queue.

Btw, if it is important, you may go to `~/.local/share/gnome-shell/extensions/keyboard_modifiers_status@sneetsher/` in your files and edit `extension.js` directly. No harm.

**Comment by thien-do** [comment]
Yes thank you @sneetsher :D it's very great that you have the "manual" section in the README! I've just cloned this repo into that folder and it works perfectly!
