### ISSUE TITLE
Support for GNOME 40?

### ISSUE THREAD

**Issue by bhootd** [sneetsher/keyboard_modifiers_status#8]
The extension is listed as incompatible for GNOME 40.

**Comment by sneetsher** [comment]
Thank you @jayesh-bhoot  for reporting this.

I added 4.00 to 4.10 . Be aware that the current implementation works only with X11. Wayland is not supported yet, due change in GDK  API Report #5

**Comment by sneetsher** [comment]
Hi @jayesh-bhoot , a fix  was just released and available from gnome  extension portal. Have nice day. by version 12
