### ISSUE TITLE
Misses fast third (release) keypress

### ISSUE THREAD

**Issue by robertvazan** [sneetsher/keyboard_modifiers_status#9]
I am talking about double-pressing modifiers, e.g. Shift Shift g n o m e Shift to type GNOME. The final (third) press of the modifier key is sometimes ignored by the extension even though the system observes it and behaves correctly. The extension can only see the final press if the key is held down a bit longer as if it is polling keyboard state at low frequency.

The system is running Fedora 35 with Wayland and GNOME 41.5.

**Comment by jezek** [comment]
I confirm this behavior on Manjaro with Wayland and GNOME 41.5.

**Comment by sneetsher** [comment]
Thank you @robertvazan  for reporting and @jezek  to confirming in another distribution that helps.

I could confirm it too, with Ubuntu 21.10 running Wayland and Not with Xorg.

```
$ gnome-shell --version
GNOME Shell 40.5
```

**Comment by sneetsher** [comment]
The fix has been released to gnome too.

**Comment by robertvazan** [comment]
It works. Thank you for super fast response.
